name: Scrape Duolingo API
on:
  schedule:
    - cron: '0 0,8,16 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to commit and push changes to the repository
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
      - name: Create JSON directory
        run: mkdir -p json
      - name: Scrape API and append to JSON
        run: |
          usernames=("Margherita427254" "Katarina451478" "000980.98dceJWb" "Kesi271320" "Aleksandra304260" "mw9R16" "JoSerrao1" "MongBalzs1" "Gosia651728" "SvitlanaDol" "ClaudiaVan847027" "ThomasSena12" "Marco253734" "Kristin131790" "Martial576200" "EaJK3" "Daniela172883" "detached" "Andrea231616" "Solky13" "Agnes312826" "tauferer" "Fabienne886023" "RosaNinja" "Inger436396" "Flo318108" "Esther301073" "Mashaagoyo" "Mathias419853" "SebGru")
          for username in "${usernames[@]}"; do
            api_response=$(curl -s "https://www.duolingo.com/2017-06-30/users?username=${username}")
            
            # Error checking
            if [[ -z "$api_response" ]]; then
              echo "No response for username: ${username}"
              continue
            elif [[ $api_response == *"error"* || $api_response == *"not found"* ]]; then
              echo "Error or not found for username: ${username}"
              continue
            fi

            # File handling with timestamp
            timestamp=$(date +"%Y-%m-%dT%H:%M:%S")
            json_file="json/${username}.json"
            echo "{\"timestamp\": \"${timestamp}\", \"data\": ${api_response}}" >> "$json_file"
          done
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add json/
          git commit -m "Update JSON data" -a || echo "No changes to commit"
          git pull --rebase  # Pull the latest changes and rebase
          git push || echo "No changes to push"
